title: John Doe
name: John Doe
description: Site description goes here.
permalink: /posts/:year/:month/:day/:title/

baseurl: "/clean-jekyll-theme"
url: ""
lang: "en"

github_username:  johndoe

social:
    name: John Doe
    links:
        - https://twitter.com/johndoe
        - https://github.com/johndoe

# Build settings
markdown: kramdown
theme: clean-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
