title: Kent Ridge AI
email: kentridgeai@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the Kent Ridge AI group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kentridgeai

# Build settings
theme: clean-jekyll-theme
plugins:
  - jekyll-feed